/*
 * ReportConsumptionFrm.java
 *
 * Created on August 3, 2008, 9:24 PM
 */
package sicce.ui.manager.reports;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.ResourceMap;
import sicce.api.businesslogic.KwValueBizObject;
import sicce.api.businesslogic.TaxBizObject;
import sicce.api.dataaccess.KwValueDAO;
import sicce.api.dataaccess.KwValueDB;
import sicce.api.dataaccess.TaxDAO;
import sicce.api.dataaccess.TaxDB;
import sicce.api.dataaccess.ReportDAO;
import sicce.api.info.ConstantsProvider;
import sicce.api.info.interfaces.IKwValue;
import sicce.api.info.interfaces.ITax;
import sicce.api.info.interfaces.IUserSicce;
import sicce.ui.manager.controls.JOptionPaneExtended;

/**
 *
 * @author  karu
 */
public class ReportConsumptionFrm extends javax.swing.JFrame {

    /** Creates new form ReportConsumptionFrm */
    private static Double costPeriod1;
    private static Double costPeriod2;
    GenerateStaticReport staticReport;
    private static ResourceMap resourceMap;
    private static IUserSicce currentUser;
    private static Map parameters;
    private IKwValue kwvalueRegister;

    public ReportConsumptionFrm(ResourceMap resourceMap, IUserSicce currentUser) {
        try {
            initComponents();
            this.resourceMap = resourceMap;
            this.currentUser = currentUser;

            addJDateListener();


        } catch (Exception ex) {
            Logger.getLogger(ReportConsumptionFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dtpStartDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dtpEndDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKwhPeriod2 = new javax.swing.JTextField();
        txtKwhPeriod1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rbLocation = new javax.swing.JRadioButton();
        rbZone = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rbUser = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.ui.manager.forms.SicceuimanagerApp.class).getContext().getResourceMap(ReportConsumptionFrm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dtpStartDate.setName("dtpStartDate"); // NOI18N
        jPanel1.add(dtpStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, -1));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 120, -1));

        dtpEndDate.setName("dtpEndDate"); // NOI18N
        jPanel1.add(dtpEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 100, -1));

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnGenerate.setText(resourceMap.getString("btnGenerate.text")); // NOI18N
        btnGenerate.setName("btnGenerate"); // NOI18N
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(null);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 30, 72, 14);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 50, 72, 14);

        txtKwhPeriod2.setEnabled(false);
        txtKwhPeriod2.setName("txtKwhPeriod2"); // NOI18N
        jPanel2.add(txtKwhPeriod2);
        txtKwhPeriod2.setBounds(90, 50, 100, 20);

        txtKwhPeriod1.setText(resourceMap.getString("txtKwhPeriod1.text")); // NOI18N
        txtKwhPeriod1.setEnabled(false);
        txtKwhPeriod1.setName("txtKwhPeriod1"); // NOI18N
        jPanel2.add(txtKwhPeriod1);
        txtKwhPeriod1.setBounds(90, 20, 100, 20);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel6.border.title"))); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        buttonGroup1.add(rbLocation);
        rbLocation.setText(resourceMap.getString("rbLocation.text")); // NOI18N
        rbLocation.setName("rbLocation"); // NOI18N

        buttonGroup1.add(rbZone);
        rbZone.setText(resourceMap.getString("rbZone.text")); // NOI18N
        rbZone.setName("rbZone"); // NOI18N
        rbZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbZoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbZone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLocation)
                    .addComponent(rbZone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        buttonGroup1.add(rbUser);
        rbUser.setText(resourceMap.getString("rbUser.text")); // NOI18N
        rbUser.setName("rbUser"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbUser)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rbUser)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGenerate)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerate)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void rbZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbZoneActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_rbZoneActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        double totalTax = 0;
        if (rbLocation.isSelected() || rbZone.isSelected() || rbUser.isSelected()) {
            ReportDAO report = new ReportDAO();
            Map parameters = new HashMap();
            staticReport = new GenerateStaticReport(resourceMap);

            parameters.put("iduser", currentUser.getIdUserSicce());
            parameters.put("startDate", dtpStartDate.getDate());
            parameters.put("endDate", dtpEndDate.getDate());
            parameters.put("costPr1", costPeriod1);
            parameters.put("costPr2", costPeriod2);


            report.callSpConsumption(dtpStartDate.getDate(), dtpEndDate.getDate());
            if (rbUser.isSelected()) {
                staticReport.GenerateStaticIndividualConsumptionReport(null, parameters);
            } else {
                List<ITax> taxes = new ArrayList<ITax>();
                taxes = TaxDB.GetTaxValueForDates(dtpStartDate.getDate(), dtpEndDate.getDate());
                for (ITax tax : taxes) {
                    totalTax = totalTax + tax.getTaxValue();
                }
                parameters.put("totalTax", totalTax);
                staticReport.GenerateStaticTotalConsumptionReport(null, rbLocation.isSelected(), rbZone.isSelected(), parameters);
            }

        } else {
            JOptionPaneExtended.showMessageDialog(null, "Seleccione el tipo de Reporte");
        }
}//GEN-LAST:event_btnGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ReportConsumptionFrm(resourceMap, currentUser).setVisible(true);
            }
        });
    }

    public void addJDateListener() {

        dtpEndDate.addPropertyChangeListener(new PropertyChangeListener() {

            public void propertyChange(PropertyChangeEvent propertyChangeEvent) {
                if (!propertyChangeEvent.getPropertyName().equals("date")) {
                    return;
                }

                if (dtpStartDate.getDate() != null && dtpEndDate.getDate() != null) {
                    kwvalueRegister = null;
                    List<IKwValue> kwvalues = new ArrayList<IKwValue>();
                    kwvalues = KwValueDB.GetKWValueForDates(dtpStartDate.getDate(), dtpEndDate.getDate());
                    if (!kwvalues.isEmpty()) {
                        kwvalueRegister = kwvalues.get(0);
                    }
                }
                if (kwvalueRegister == null) {
                    JOptionPaneExtended.showMessageDialog(null, "No existen costos para el rango definido");
                    txtKwhPeriod1.setText("");
                    txtKwhPeriod2.setText("");
                    return;
                } else {
                    txtKwhPeriod1.setText(kwvalueRegister.getKwValue1().toString());
                    txtKwhPeriod2.setText(kwvalueRegister.getKwValue2().toString());
                    costPeriod1 = kwvalueRegister.getKwValue1();
                    costPeriod2 = kwvalueRegister.getKwValue2();

                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dtpEndDate;
    private com.toedter.calendar.JDateChooser dtpStartDate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton rbLocation;
    private javax.swing.JRadioButton rbUser;
    private javax.swing.JRadioButton rbZone;
    private javax.swing.JTextField txtKwhPeriod1;
    private javax.swing.JTextField txtKwhPeriod2;
    // End of variables declaration//GEN-END:variables
}
