/*
 * LocationPane.java
 *
 * Created on January 26, 2008, 7:43 PM
 */

package sicce.ui.manager.forms;

import sicce.api.businesslogic.ClassFactory;

import sicce.api.businesslogic.LocationTypeBizObject;
import sicce.api.businesslogic.SicceComboBoxModel;
import sicce.api.businesslogic.SicceComboBoxRenderer;
import sicce.api.dataaccess.LocationDB;
import sicce.api.info.ConstantsProvider.DisplayMemberRenderType;
import sicce.api.info.interfaces.ILocation;
import sicce.api.info.interfaces.ILocationType;
import sicce.api.util.ComponentUtil;
import sicce.ui.manager.controls.JTabExtended;

/**
 *
 * @author  gish@c
 */
public class LocationPane extends JTabExtended {
    
    SicceComboBoxModel<ILocationType> locationTypeComboBoxModel;
    SicceComboBoxRenderer locationTypeComboBoxRenderer;
    LocationTypeBizObject locationTypeBizObject;
    private ILocation location;
    
    /** Creates new form LocationPane */
    public LocationPane() {
        initComponents();
        getControlsToClear().add(txtDescription);
        getControlsToClear().add(txtUbication); 
        getControlsToClear().add(txtPowerMeter);
        getControlsToClear().add(btnSearchPowerMeter);
        getControlsToClear().add(btnSearchUbication);
        getControlsToClear().add(cmbLocationType);
        getControlsToEnable().add(txtDescription);
        getControlsToEnable().add(txtUbication);
        getControlsToEnable().add(txtPowerMeter);
        getControlsToEnable().add(btnSearchPowerMeter);
        getControlsToEnable().add(btnSearchUbication);
        getControlsToEnable().add(cmbLocationType);
        ComponentUtil.SetState(false, getControlsToEnable());
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblUbication = new javax.swing.JLabel();
        txtUbication = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblDescription2 = new javax.swing.JLabel();
        btnSearchUbication = new javax.swing.JButton();
        lblLocationType = new javax.swing.JLabel();
        lblPowerMeter = new javax.swing.JLabel();
        txtPowerMeter = new javax.swing.JTextField();
        btnSearchPowerMeter = new javax.swing.JButton();
        cmbLocationType = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdLocation = new javax.swing.JTable();

        setName("Form"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.ui.manager.forms.SicceuimanagerApp.class).getContext().getResourceMap(LocationPane.class);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(null);

        lblUbication.setText(resourceMap.getString("lblUbication.text")); // NOI18N
        lblUbication.setName("lblUbication"); // NOI18N
        jPanel4.add(lblUbication);
        lblUbication.setBounds(10, 30, 49, 14);

        txtUbication.setName("txtUbication"); // NOI18N
        jPanel4.add(txtUbication);
        txtUbication.setBounds(120, 30, 140, 20);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setName("txtDescription"); // NOI18N
        jScrollPane4.setViewportView(txtDescription);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(120, 140, 200, 76);

        lblDescription2.setText(resourceMap.getString("lblDescription2.text")); // NOI18N
        lblDescription2.setName("lblDescription2"); // NOI18N
        jPanel4.add(lblDescription2);
        lblDescription2.setBounds(10, 140, 58, 14);

        btnSearchUbication.setIcon(resourceMap.getIcon("btnSearchUbication.icon")); // NOI18N
        btnSearchUbication.setText(resourceMap.getString("btnSearchUbication.text")); // NOI18N
        btnSearchUbication.setAlignmentX(0.5F);
        btnSearchUbication.setAlignmentY(1.5F);
        btnSearchUbication.setName("btnSearchUbication"); // NOI18N
        btnSearchUbication.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSearchUbication.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(btnSearchUbication);
        btnSearchUbication.setBounds(270, 20, 30, 30);

        lblLocationType.setText(resourceMap.getString("lblLocationType.text")); // NOI18N
        lblLocationType.setName("lblLocationType"); // NOI18N
        jPanel4.add(lblLocationType);
        lblLocationType.setBounds(10, 70, 120, 14);

        lblPowerMeter.setText(resourceMap.getString("lblPowerMeter.text")); // NOI18N
        lblPowerMeter.setName("lblPowerMeter"); // NOI18N
        jPanel4.add(lblPowerMeter);
        lblPowerMeter.setBounds(10, 110, 120, 14);

        txtPowerMeter.setName("txtPowerMeter"); // NOI18N
        jPanel4.add(txtPowerMeter);
        txtPowerMeter.setBounds(120, 110, 140, 20);

        btnSearchPowerMeter.setIcon(resourceMap.getIcon("btnSearchPowerMeter.icon")); // NOI18N
        btnSearchPowerMeter.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSearchPowerMeter.setName("btnSearchPowerMeter"); // NOI18N
        jPanel4.add(btnSearchPowerMeter);
        btnSearchPowerMeter.setBounds(270, 100, 30, 30);

        cmbLocationType.setName("cmbLocationType"); // NOI18N
        jPanel4.add(cmbLocationType);
        cmbLocationType.setBounds(120, 60, 180, 20);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        grdLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Object", "Ubicación", "Tipo de Dependencia", "Medidor", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grdLocation.setName("grdLocation"); // NOI18N
        jScrollPane1.setViewportView(grdLocation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         locationTypeBizObject = new LocationTypeBizObject();
        locationTypeComboBoxModel = new SicceComboBoxModel<ILocationType>(locationTypeBizObject.GetAllLocationsType());
        locationTypeComboBoxRenderer = new SicceComboBoxRenderer("getDescription", DisplayMemberRenderType.Method);
        cmbLocationType.setModel(locationTypeComboBoxModel);
        cmbLocationType.setRenderer(locationTypeComboBoxRenderer);
    }//GEN-LAST:event_formComponentShown
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchPowerMeter;
    private javax.swing.JButton btnSearchUbication;
    private javax.swing.JComboBox cmbLocationType;
    private javax.swing.JTable grdLocation;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDescription2;
    private javax.swing.JLabel lblLocationType;
    private javax.swing.JLabel lblPowerMeter;
    private javax.swing.JLabel lblUbication;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtPowerMeter;
    private javax.swing.JTextField txtUbication;
    // End of variables declaration//GEN-END:variables
   
      @Override
    public void Back() {
        super.Back();
    }

    @Override
    public boolean Delete() throws Exception {
        cancelAction = false;
        try {
            super.Delete();              
            LocationDB.Delete(location);
            
        } catch (Exception ex) {
            cancelAction = true;
            throw ex;
        }
        return cancelAction;
    }

    @Override
    public void New() {
        super.New();
        location = ClassFactory.getLocationInstance();
        txtDescription.requestFocusInWindow();
    }

    @Override
    public boolean Save() throws Exception {
        cancelAction = false;        
        try {
            location.setDescription(txtDescription.getText().trim());
            if (IsObjectLoaded()) {
                return Update();
            }
            location = LocationDB.Save(location);
           // txtCode.setText(String.valueOf(locationType.getID()));
        } catch (Exception ex) {
            cancelAction = true;
        }
        return cancelAction;
    }

    @Override
    public void Search() {
        super.Search();
    }

    @Override
    public boolean Update() throws Exception {
        cancelAction = false;
        try {
            LocationDB.Update(location);
        } catch (Exception ex) {
            cancelAction = true;
        }
        return cancelAction;
    }
    
    
    
    
    
    
}
