/*
 * ReportsPane.java
 *
 * Created on 16 de junio de 2008, 23:57
 */

package sicce.ui.manager.forms;

import javax.swing.JScrollPane;
import org.jdesktop.application.ResourceMap;
import sicce.api.businesslogic.ReportBizObject;
import sicce.api.businesslogic.ReportTableModel;
import sicce.api.info.interfaces.IReport;
import sicce.ui.manager.controls.JTabExtended;
import sicce.api.dataaccess.ReportDB;
import sicce.api.info.ToolBarStateInfo;
import sicce.ui.manager.controls.ReportTable;

/**
 *
 * @author  Karu
 */
public class ReportsPane extends JTabExtended<IReport> {
    
    ReportBizObject reportBizObj;
    ReportTableModel reportModel;
    private ReportTable grdReport;
    private JScrollPane jScrollPane1;
    
    /** Creates new form ReportsPane */
    public ReportsPane(ResourceMap resourceMap) {
        initComponents();
        this.resourceMap = resourceMap;
        grdReport = new ReportTable(resourceMap);
        jScrollPane1 = new JScrollPane();
        jScrollPane1.setViewportView(grdReport);
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 180));
         reportBizObj = new ReportBizObject();
        this.setHandleToolBarStates(false);
        this.setToolBarStateInfo(new ToolBarStateInfo(false, false, false, false, false, false));
        FillGrid();
         
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setName("Form"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.ui.manager.forms.SicceuimanagerApp.class).getContext().getResourceMap(ReportsPane.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 390, 210));
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
  @Override
    public boolean Delete() throws Exception {
        cancelAction = false;
        try {
            super.Delete();
            ReportDB.Delete(currentObject);
            FillGrid();
        } catch (Exception ex) {
            cancelAction = true;
            throw ex;
        }
        return cancelAction;
    }

    
  
    @Override
    public void FillGrid() {
        reportModel = new ReportTableModel(reportBizObj.GetAllReport());
        grdReport.setModel(reportModel);
    }

  
  
    
    
}
