package sicce.api.info;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import sicce.api.info.auto.AbstractMeasure;

/**
 * Measure generated by MyEclipse Persistence Tools
 */
public class Measure extends AbstractMeasure implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Measure() {
	}

	/** minimal constructor */
	public Measure(Integer idMeasure, PowerMeter powerMeter, Location location,
			UnitMeasure unitMeasure) {
		super(idMeasure, powerMeter, location, unitMeasure);
	}

	/** full constructor */
	public Measure(Integer idMeasure, PowerMeter powerMeter, Location location,
			UnitMeasure unitMeasure, Long value, Date dateMeasure) {
		super(idMeasure, powerMeter, location, unitMeasure, value, dateMeasure);
	}

}
