package sicce.api.info;

// Generated by MyEclipse Persistence Tools
import java.util.Comparator;
import java.util.Set;

import sicce.api.info.auto.AbstractOptionSicce;
import sicce.api.info.interfaces.IOptionSicce;
import sicce.api.info.interfaces.IRole;

/**
 * OptionSicce generated by MyEclipse Persistence Tools
 */
public class OptionSicce extends AbstractOptionSicce implements
        java.io.Serializable, IOptionSicce, Comparable {

    // Constructors
    /** default constructor */
    public OptionSicce() {
    }

    /** minimal constructor */
    public OptionSicce(Integer idOptionSicce) {
        super(idOptionSicce);
    }

    /** full constructor */
    public OptionSicce(Integer idOptionSicce, String description, String icon,
            Set<IRole> roles) {
        super(idOptionSicce, description, icon, roles);
    }

    public int getID() {
        return super.getIdOptionSicce();
    }

   
    /**
     * 
     * @param o
     * @return
     */
    public int compareTo(Object option) {
        IOptionSicce optionSicce = (IOptionSicce) option;
        return this.getDescription().compareTo(optionSicce.getDescription());
    }
}
