package sicce.api.info;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

import sicce.api.info.auto.AbstractUnitMeasure;

/**
 * UnitMeasure generated by MyEclipse Persistence Tools
 */
public class UnitMeasure extends AbstractUnitMeasure implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public UnitMeasure() {
	}

	/** minimal constructor */
	public UnitMeasure(Integer idUnitMeasure) {
		super(idUnitMeasure);
	}

	/** full constructor */
	public UnitMeasure(Integer idUnitMeasure, String description, Set<Measure> measures) {
		super(idUnitMeasure, description, measures);
	}

}
