package sicce.api.info;

import sicce.api.info.auto.AbstractUserSicce;

// Generated by MyEclipse Persistence Tools
import sicce.api.info.interfaces.IRole;
import sicce.api.info.interfaces.IUserSicce;

/**
 * UserSicce generated by MyEclipse Persistence Tools
 */
public class UserSicce extends AbstractUserSicce implements
        java.io.Serializable, IUserSicce {

    // Constructors
    /** default constructor */
    public UserSicce() {
    }

    /** minimal constructor */
    public UserSicce(Integer idUserSicce, IRole role) {
        super(idUserSicce, role);
    }

    /** full constructor */
    public UserSicce(Integer idUserSicce, IRole role, String name,
            String lastname, Integer codeUcsg, String usernameSicce,
            String passwordSicce) {
        super(idUserSicce, role, name, lastname, codeUcsg, usernameSicce,
                passwordSicce);
    }

    public Integer getID() {
        return super.getIdUserSicce();
    }
}
