/*tabla user_sicce
el foraneo entre user_sicce y role cambio de _ID_ROLE  a ID_ROLE

tabla measure
el foraneo entre location y measure cambio de LOCATION_ID_LOCATION a ID_LOCATION

tabla Location 
los campos location y code fueron eliminados*/



drop table user_sicce;
drop table measure;

alter table `sicce`.`location` drop column `CODE`, drop column `LOCATION`;


CREATE TABLE MEASURE (
  ID_MEASURE INTEGER UNSIGNED NOT NULL,
  ID_LOCATION INTEGER UNSIGNED NOT NULL,
  ID_POWER_METER INTEGER UNSIGNED NOT NULL,
  VALUE DECIMAL NULL,
  DATE_MEASURE DATETIME NULL,
  PRIMARY KEY(ID_MEASURE),
  INDEX MEASURE_FKIndex1(ID_MEASURE),
  INDEX MEASURE_FKIndex2(ID_POWER_METER),
  INDEX MEASURE_FKIndex3(ID_LOCATION),
  FOREIGN KEY(ID_MEASURE)
    REFERENCES UNIT_MEASURE(ID_UNIT_MEASURE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_POWER_METER)
    REFERENCES POWER_METER(ID_POWER_METER)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_LOCATION)
    REFERENCES LOCATION(ID_LOCATION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE USER_SICCE (
  ID_USER_SICCE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_ROLE INTEGER UNSIGNED NOT NULL,
  NAME VARCHAR(20) NULL,
  LASTNAME VARCHAR(20) NULL,
  CODE_UCSG INTEGER UNSIGNED NULL,
  USERNAME_SICCE VARCHAR(20) NULL,
  PASSWORD_SICCE VARCHAR(20) NULL,
  PRIMARY KEY(ID_USER_SICCE),
  INDEX USER_SICCE_FKIndex1(ID_ROLE),
  FOREIGN KEY(ID_ROLE)
    REFERENCES ROLE(ID_ROLE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


