CREATE TABLE POWER_METER (
  ID_POWER_METER INT   NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(255) NULL,
  IP_ADDRESS VARCHAR(20)   NULL,
  LOG_STATUS BOOL NULL,
  SERIAL VARCHAR(20) NULL,
  STATUS_2 BOOL NULL,
  PRIMARY KEY(ID_POWER_METER)
);

CREATE TABLE PARAMETER (
  ID_PARAMETER INT   NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(45) NULL,
  VALUE DECIMAL NULL,
  PRIMARY KEY(ID_PARAMETER)
);

CREATE TABLE ROLE (
  ID_ROLE INT   NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(20) NULL,
  PRIMARY KEY(ID_ROLE)
);

CREATE TABLE ZONE (
  ID_ZONE INT ZEROFILL NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(20) NULL,
  PRIMARY KEY(ID_ZONE)
);

CREATE TABLE UNIT_MEASURE (
  ID_UNIT_MEASURE INT   NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(45) NULL,
  PRIMARY KEY(ID_UNIT_MEASURE)
);

CREATE TABLE OPTION_SICCE (
  ID_OPTION_SICCE INT   NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(30) NULL,
  ICON BLOB NULL,
  PRIMARY KEY(ID_OPTION_SICCE)
);

CREATE TABLE LOCATION_TYPE (
  ID_LOCATION_TYPE INT   NOT NULL AUTO_INCREMENT,
  DESCRIPTION INT   NULL,
  PRIMARY KEY(ID_LOCATION_TYPE)
);

CREATE TABLE USER_SICCE (
  ID_USER_SICCE INT   NOT NULL AUTO_INCREMENT,
  ROLE_ID_ROLE INT   NOT NULL,
  NAME VARCHAR(20) NULL,
  SURNAME VARCHAR(20) NULL,
  CODE_UCSG INT   NULL,
  USERNAME_SICCE VARCHAR(20) NULL,
  PASSWORD_SICCE VARCHAR(20) NULL,
  PRIMARY KEY(ID_USER_SICCE),
  INDEX USER_SICCE_FKIndex1(ROLE_ID_ROLE),
  FOREIGN KEY(ROLE_ID_ROLE)
    REFERENCES ROLE(ID_ROLE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE LOCATION (
  ID_LOCATION INT   NOT NULL AUTO_INCREMENT,
  POWER_METER_ID_POWER_METER INT   NOT NULL,
  PARENT_ID_LOCATION INT   NOT NULL,
  ID_LOCATION_TYPE INT   NOT NULL,
  DESCRIPTION VARCHAR(255) NULL,
  LOCATION INT   NULL,
  PRIMARY KEY(ID_LOCATION),
  INDEX Ubication_FKIndex2(PARENT_ID_LOCATION),
  INDEX LOCATION_FKIndex2(ID_LOCATION_TYPE),
  INDEX LOCATION_FKIndex3(POWER_METER_ID_POWER_METER),
  FOREIGN KEY(PARENT_ID_LOCATION)
    REFERENCES LOCATION(ID_LOCATION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_LOCATION_TYPE)
    REFERENCES LOCATION_TYPE(ID_LOCATION_TYPE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(POWER_METER_ID_POWER_METER)
    REFERENCES POWER_METER(ID_POWER_METER)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE OPTION_ROLE (
  ID_ROLE INT   NOT NULL,
  ID_OPTION_SICCE INT   NOT NULL,
  INDEX OPTION_ROLE_FKIndex1(ID_OPTION_SICCE),
  INDEX OPTION_ROLE_FKIndex2(ID_ROLE),
  FOREIGN KEY(ID_OPTION_SICCE)
    REFERENCES OPTION_SICCE(ID_OPTION_SICCE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_ROLE)
    REFERENCES ROLE(ID_ROLE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE LOCATION_ZONE (
  ID_LOCATION INT   NOT NULL,
  ID_ZONE INT ZEROFILL NOT NULL,
  INDEX LOCATION_ZONE_FKIndex1(ID_ZONE),
  INDEX LOCATION_ZONE_FKIndex2(ID_LOCATION),
  FOREIGN KEY(ID_ZONE)
    REFERENCES ZONE(ID_ZONE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_LOCATION)
    REFERENCES LOCATION(ID_LOCATION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE MEASURE (
  ID_MEASURE INT   NOT NULL,
  LOCATION_ID_LOCATION INT   NOT NULL,
  ID_POWER_METER INT   NOT NULL,
  VALUE DECIMAL NULL,
  DATE_MEASURE DATETIME NULL,
  PRIMARY KEY(ID_MEASURE),
  INDEX MEASURE_FKIndex1(ID_MEASURE),
  INDEX MEASURE_FKIndex2(ID_POWER_METER),
  INDEX MEASURE_FKIndex3(LOCATION_ID_LOCATION),
  FOREIGN KEY(ID_MEASURE)
    REFERENCES UNIT_MEASURE(ID_UNIT_MEASURE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_POWER_METER)
    REFERENCES POWER_METER(ID_POWER_METER)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(LOCATION_ID_LOCATION)
    REFERENCES LOCATION(ID_LOCATION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


