package sicce.api.info.cayenne.auto;

/** Class _OptionRole was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _OptionRole extends org.apache.cayenne.CayenneDataObject {

    public static final String TO_OPTION_SICCE_PROPERTY = "toOptionSicce";
    public static final String TO_ROLE_PROPERTY = "toRole";


    public void setToOptionSicce(sicce.api.info.OptionSicceInfo toOptionSicce) {
        setToOneTarget("toOptionSicce", toOptionSicce, true);
    }

    public sicce.api.info.OptionSicceInfo getToOptionSicce() {
        return (sicce.api.info.OptionSicceInfo)readProperty("toOptionSicce");
    } 
    
    
    public void setToRole(sicce.api.info.RoleInfo toRole) {
        setToOneTarget("toRole", toRole, true);
    }

    public sicce.api.info.RoleInfo getToRole() {
        return (sicce.api.info.RoleInfo)readProperty("toRole");
    } 
    
    
}
