/*
 * SicceapiprocessorviewerView.java
 */
package sicce.api.processor.viewer;

import java.awt.BorderLayout;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import sicce.api.processor.Processor;
import sicce.api.processor.viewer.controls.ChartPane;
import sicce.api.processor.viewer.controls.LogPane;

/**
 * The application's main frame.
 */
public class SicceapiprocessorviewerView extends FrameView {

    public SicceapiprocessorviewerView(SingleFrameApplication app) {
        super(app);

        initComponents();
        OrganizeUIElements();
        BuildPanes();
        RunProcessor();
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = SicceapiprocessorviewerApp.getApplication().getMainFrame();
            aboutBox = new SicceapiprocessorviewerAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        SicceapiprocessorviewerApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        mainPanel.setName("mainPanel"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    private JDialog aboutBox;
    
    private JTabbedPane tabManager;
    
    /**
     * gish@c
     * Retorna la instancia del control que administra los tabs
     */
    public JTabbedPane getTabManager() {
        if (tabManager == null) {
            tabManager = new JTabbedPane();
        }
        return tabManager;
    }
    
    /**
     * 
     */
    private void OrganizeUIElements(){
        this.getFrame().getContentPane().add(getTabManager(), BorderLayout.CENTER);
    }

    /**
     * 
     */
    private void BuildPanes(){
        ChartPane chartPane = new ChartPane(getResourceMap().getString("ChartTitle"));
        LogPane logPane = new LogPane();
        getTabManager().addTab("Gráficos del Consumo Eléctrico", chartPane);
        getTabManager().addTab("Log de Lecturas del Consumo Eléctrico", logPane);
    }
   
    
    /**
     * 
     */
    private void RunProcessor(){
        Processor.DoProcess();
    }
}
