/*
 * LocationPane.java
 *
 * Created on January 26, 2008, 7:43 PM
 */

package sicce.ui.manager.forms;

import sicce.ui.manager.controls.JTabExtended;

/**
 *
 * @author  gish@c
 */
public class LocationPane extends JTabExtended {
    
    /** Creates new form LocationPane */
    public LocationPane() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblUbication = new javax.swing.JLabel();
        txtUbication = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescription2 = new javax.swing.JTextArea();
        lblDescription2 = new javax.swing.JLabel();
        btnSearchUbication = new javax.swing.JButton();
        lblLocationType = new javax.swing.JLabel();
        txtLocationType = new javax.swing.JTextField();
        btnSearchLocationType = new javax.swing.JButton();
        lblPowerMeter = new javax.swing.JLabel();
        txtPowerMeter = new javax.swing.JTextField();
        btnSearchPowerMeter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdLocation = new javax.swing.JTable();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.ui.manager.forms.SicceuimanagerApp.class).getContext().getResourceMap(LocationPane.class);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(null);

        lblUbication.setText(resourceMap.getString("lblUbication.text")); // NOI18N
        lblUbication.setName("lblUbication"); // NOI18N
        jPanel4.add(lblUbication);
        lblUbication.setBounds(10, 30, 49, 14);

        txtUbication.setName("txtUbication"); // NOI18N
        jPanel4.add(txtUbication);
        txtUbication.setBounds(120, 30, 140, 20);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        txtDescription2.setColumns(20);
        txtDescription2.setRows(5);
        txtDescription2.setName("txtDescription2"); // NOI18N
        jScrollPane4.setViewportView(txtDescription2);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(120, 140, 200, 19);

        lblDescription2.setText(resourceMap.getString("lblDescription2.text")); // NOI18N
        lblDescription2.setName("lblDescription2"); // NOI18N
        jPanel4.add(lblDescription2);
        lblDescription2.setBounds(10, 140, 58, 14);

        btnSearchUbication.setIcon(resourceMap.getIcon("btnSearchUbication.icon")); // NOI18N
        btnSearchUbication.setText(resourceMap.getString("btnSearchUbication.text")); // NOI18N
        btnSearchUbication.setAlignmentX(0.5F);
        btnSearchUbication.setAlignmentY(1.5F);
        btnSearchUbication.setName("btnSearchUbication"); // NOI18N
        btnSearchUbication.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSearchUbication.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(btnSearchUbication);
        btnSearchUbication.setBounds(270, 20, 30, 30);

        lblLocationType.setText(resourceMap.getString("lblLocationType.text")); // NOI18N
        lblLocationType.setName("lblLocationType"); // NOI18N
        jPanel4.add(lblLocationType);
        lblLocationType.setBounds(10, 70, 120, 14);

        txtLocationType.setName("txtLocationType"); // NOI18N
        jPanel4.add(txtLocationType);
        txtLocationType.setBounds(120, 70, 140, 20);

        btnSearchLocationType.setIcon(resourceMap.getIcon("btnSearchLocationType.icon")); // NOI18N
        btnSearchLocationType.setName("btnSearchLocationType"); // NOI18N
        jPanel4.add(btnSearchLocationType);
        btnSearchLocationType.setBounds(270, 60, 30, 30);

        lblPowerMeter.setText(resourceMap.getString("lblPowerMeter.text")); // NOI18N
        lblPowerMeter.setName("lblPowerMeter"); // NOI18N
        jPanel4.add(lblPowerMeter);
        lblPowerMeter.setBounds(10, 110, 120, 14);

        txtPowerMeter.setName("txtPowerMeter"); // NOI18N
        jPanel4.add(txtPowerMeter);
        txtPowerMeter.setBounds(120, 110, 140, 20);

        btnSearchPowerMeter.setIcon(resourceMap.getIcon("btnSearchPowerMeter.icon")); // NOI18N
        btnSearchPowerMeter.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSearchPowerMeter.setName("btnSearchPowerMeter"); // NOI18N
        jPanel4.add(btnSearchPowerMeter);
        btnSearchPowerMeter.setBounds(270, 100, 30, 30);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        grdLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Object", "Ubicación", "Tipo de Dependencia", "Medidor", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grdLocation.setName("grdLocation"); // NOI18N
        jScrollPane1.setViewportView(grdLocation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchLocationType;
    private javax.swing.JButton btnSearchPowerMeter;
    private javax.swing.JButton btnSearchUbication;
    private javax.swing.JTable grdLocation;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblCode1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblDescription2;
    private javax.swing.JLabel lblLocationType;
    private javax.swing.JLabel lblPowerMeter;
    private javax.swing.JLabel lblUbication;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCode1;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtDescription1;
    private javax.swing.JTextArea txtDescription2;
    private javax.swing.JTextField txtLocationType;
    private javax.swing.JTextField txtPowerMeter;
    private javax.swing.JTextField txtUbication;
    // End of variables declaration//GEN-END:variables
    
}
