/*
 * PowerMeterPane.java
 *
 * Created on January 23, 2008, 12:39 AM
 */

package sicce.ui.manager.forms;

import sicce.ui.manager.controls.JTabExtended;

/**
 *
 * @author  gish@c
 */
public class PowerMeterPane extends JTabExtended {
    
    /** Creates new form PowerMeterPane */
    public PowerMeterPane() {
        initComponents();
    }
    
    /** Creates new form PowerMeterPane */
    public PowerMeterPane(Object option) {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("PowerMeterPane"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
