/*
 * TaxPane.java
 *
 * Created on October 1, 2008, 12:37 AM
 */
package sicce.ui.manager.forms;

import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import sicce.api.businesslogic.TaxBizObject;
import sicce.api.businesslogic.factory.ClassFactory;
import sicce.api.businesslogic.model.SicceTableModel;
import sicce.api.businesslogic.model.TaxTableModel;
import sicce.api.dataaccess.TaxDB;
import sicce.api.info.ConstantsProvider.DialogResult;
import sicce.api.info.interfaces.ITax;
import sicce.api.util.ComponentUtil;
import sicce.api.util.JTextFieldDecimal;
import sicce.api.util.JTextFieldInteger;
import sicce.api.util.JTextFieldLimit;
import sicce.api.util.Validator;
import sicce.ui.manager.controls.JTabExtended;
import sicce.ui.manager.controls.SearchDialog;
import sicce.ui.manager.handlers.ExceptionHandler;

/**
 * Panel para la administracion de Rubros
 * @author  gish@c
 */
public class TaxPane extends JTabExtended<ITax> {

    /**
     * Modelo de tabla para mostrar los rubros existentes
     */
    private TaxTableModel taxTableModel;
    /**
     * Objeto para manejar la logica de los rubros
     */
    private TaxBizObject taxBizObject;

    /**
     * Constructor
     */
    public TaxPane() {
        initComponents();
        txtDescription.setDocument(new JTextFieldLimit(150));
        txtValue.setDocument(new JTextFieldDecimal());
        getControlsToClear().add(txtDescription);
        getControlsToClear().add(txtValue);
        getControlsToClear().add(dpStartDate);
        getControlsToClear().add(dpEndDate);
        getControlsToEnable().add(dpStartDate);
        getControlsToEnable().add(dpEndDate);
        getControlsToEnable().add(txtDescription);
        getControlsToEnable().add(txtValue);
        taxBizObject = new TaxBizObject();
        FillGrid();
        ComponentUtil.SetState(false, getControlsToEnable());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStartDate = new javax.swing.JLabel();
        dpStartDate = new com.toedter.calendar.JDateChooser();
        lblEndDate = new javax.swing.JLabel();
        dpEndDate = new com.toedter.calendar.JDateChooser();
        lblValue = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridTaxes = new javax.swing.JTable();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.ui.manager.forms.SicceuimanagerApp.class).getContext().getResourceMap(TaxPane.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        lblStartDate.setText(resourceMap.getString("lblStartDate.text")); // NOI18N
        lblStartDate.setName("lblStartDate"); // NOI18N

        dpStartDate.setEnabled(false);
        dpStartDate.setName("dpStartDate"); // NOI18N

        lblEndDate.setText(resourceMap.getString("lblEndDate.text")); // NOI18N
        lblEndDate.setName("lblEndDate"); // NOI18N

        dpEndDate.setEnabled(false);
        dpEndDate.setName("dpEndDate"); // NOI18N

        lblValue.setText(resourceMap.getString("lblValue.text")); // NOI18N
        lblValue.setName("lblValue"); // NOI18N

        txtValue.setText(resourceMap.getString("txtValue.text")); // NOI18N
        txtValue.setEnabled(false);
        txtValue.setName("txtValue"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txtDescription.setEnabled(false);
        txtDescription.setName("txtDescription"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStartDate))
                            .addComponent(lblEndDate)
                            .addComponent(lblValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValue)
                            .addComponent(dpEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dpStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartDate)
                    .addComponent(dpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEndDate)
                    .addComponent(dpEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValue)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        gridTaxes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridTaxes.setName("gridTaxes"); // NOI18N
        jScrollPane1.setViewportView(gridTaxes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dpEndDate;
    private com.toedter.calendar.JDateChooser dpStartDate;
    private javax.swing.JTable gridTaxes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
    @Override
    public boolean Delete() throws Exception {
        cancelAction = false;
        try {
            TaxDB.Delete(currentObject);
            super.Delete();
            FillGrid();

        } catch (Exception ex) {
            cancelAction = true;
            throw ex;
        }
        return cancelAction;
    }

    @Override
    public void New() {
        super.New();
        currentObject = ClassFactory.getTaxInstance();
        txtDescription.requestFocusInWindow();
    }

    @Override
    public boolean Save() throws Exception {
        super.Save();
        cancelAction = false;
        if (!CheckFields()) {
            return true;
        }
        try {
            currentObject.setDescription(txtDescription.getText().trim());
            currentObject.setTaxValue(Double.parseDouble(txtValue.getText()));
            currentObject.setStartDate(dpStartDate.getDate());
            currentObject.setEndDate(dpEndDate.getDate());
            if (IsObjectLoaded()) {
                return Update();
            }
            TaxDB.Save(currentObject);
            FillGrid();
        } catch (Exception ex) {
            ExceptionHandler.DisplayException(ex);
            cancelAction = true;
        }
        return cancelAction;
    }

    @Override
    public DialogResult Search() {
        SearchDialog<ITax> searchRolesDialog = new SearchDialog<ITax>(new JFrame(), true, new TaxTableModel(taxBizObject.GetAllTaxes()));
        searchRolesDialog.setVisible(true);
        DialogResult result = searchRolesDialog.getDialogResult();
        if (result == DialogResult.Ok) {
            currentObject = searchRolesDialog.getSearchResult();
            SetUIElements();
        }
        return result;
    }

    @Override
    public boolean Update() throws Exception {
        cancelAction = false;
        try {
            TaxDB.Update(currentObject);
            FillGrid();
        } catch (Exception ex) {
            cancelAction = true;
        }
        return cancelAction;
    }

    @Override
    public void ItemSelected(int selectedIndex) {
        super.ItemSelected(selectedIndex);
        SicceTableModel<ITax> tableModel = (SicceTableModel<ITax>) gridTaxes.getModel();
        currentObject = tableModel.getRow(selectedIndex);
        SetUIElements();
    }

    @Override
    public void RegisterSelectionListener() {
        gridTaxes.getSelectionModel().addListSelectionListener(selectionListener);
        gridTaxes.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    @Override
    public void SetUIElements() {
        if (currentObject == null) {
            return;
        }
        txtDescription.setText(currentObject.getDescription());
        txtValue.setText(currentObject.getTaxValue() != null ? currentObject.getTaxValue().toString() : "");
        dpStartDate.setDate(currentObject.getStartDate());
        dpEndDate.setDate(currentObject.getEndDate());
    }

    @Override
    public void CancelSave() {
        if (currentObject != null) {
            if (currentObject.getIdTax() == null) {
                this.currentObject = ClassFactory.getTaxInstance();
            }
        }
    }

    @Override
    public void FillGrid() {
        taxTableModel = new TaxTableModel(taxBizObject.GetAllTaxes());
        gridTaxes.setModel(taxTableModel);
    }

    @Override
    public boolean CheckFields() {
        if (!Validator.ValidateField(null, null, 0, txtDescription, true, "la descripción del rubro", 3)) {
            return false;
        }
        if (dpEndDate.getDate().compareTo(dpStartDate.getDate()) <= 0) {
            ExceptionHandler.DisplayWarning("La fecha final del rubro debe ser mayor a la fecha inicial");
            return false;
        }
        return true;
    }
}
