package sicce.api.info.auto;

import java.util.HashSet;
import java.util.Set;

import sicce.api.info.interfaces.ILocation;
import sicce.api.info.interfaces.ILocationType;
import sicce.api.info.interfaces.IMeasure;
import sicce.api.info.interfaces.IPowerMeter;
import sicce.api.info.interfaces.IZone;

/**
 * AbstractLocation generated by MyEclipse Persistence Tools
 */

public abstract class AbstractLocation implements java.io.Serializable {

	// Fields

	protected Integer idLocation;
	protected ILocationType locationType;
	protected ILocation location;
	protected IPowerMeter powerMeter;
	protected String description;
	protected Set<ILocation> locations = new HashSet<ILocation>(0);
	protected Set<IZone> zones = new HashSet<IZone>(0);
	protected Set<IMeasure> measures = new HashSet<IMeasure>(0);

	// Constructors

	/** default constructor */
	public AbstractLocation() {
	}

	/** minimal constructor */
	public AbstractLocation(Integer idLocation, ILocationType locationType,
			ILocation location, IPowerMeter powerMeter, String description) {
		this.idLocation = idLocation;
		this.locationType = locationType;
		this.location = location;
		this.powerMeter = powerMeter;
		this.description = description;
	}

	/** full constructor **/
	public AbstractLocation(Integer idLocation, ILocationType locationType,
			ILocation location, IPowerMeter powerMeter, String description,
			Set<ILocation> locations, Set<IZone> zones,
			Set<IMeasure> measures) {
		this.idLocation = idLocation;
		this.locationType = locationType;
		this.location = location;
		this.powerMeter = powerMeter;
		this.description = description;
		this.locations = locations;
		this.zones = zones;
		this.measures = measures;
	}

	// Property accessors

	public Integer getIdLocation() {
		return this.idLocation;
	}

	public void setIdLocation(Integer idLocation) {
		this.idLocation = idLocation;
	}

	public ILocationType getLocationType() {
		return this.locationType;
	}

	public void setLocationType(ILocationType locationType) {
		this.locationType = locationType;
	}

	public ILocation getLocation() {
		return this.location;
	}

	public void setLocation(ILocation location) {
		this.location = location;
	}

	public IPowerMeter getPowerMeter() {
		return this.powerMeter;
	}

	public void setPowerMeter(IPowerMeter powerMeter) {
		this.powerMeter = powerMeter;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ILocation> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<ILocation> locations) {
		this.locations = locations;
	}

	public Set<IZone> getZones() {
		return this.zones;
	}

	public void setZones(Set<IZone> zones) {
		this.zones = zones;
	}

	public Set<IMeasure> getMeasures() {
		return this.measures;
	}

	public void setMeasures(Set<IMeasure> measures) {
		this.measures = measures;
	}

}