package sicce.api.info.auto;

/**
 * AbstractParameter generated by MyEclipse Persistence Tools
 */
public abstract class AbstractParameter implements java.io.Serializable {

    // Fields
    protected Integer idParameter;
    protected String description;
    protected String value;
    private String parameterKey;

    // Constructors
    /** default constructor */
    public AbstractParameter() {
    }

    /** minimal constructor */
    public AbstractParameter(Integer idParameter) {
        this.idParameter = idParameter;
    }

    /** full constructor */
    public AbstractParameter(Integer idParameter, String description, String value) {
        this.idParameter = idParameter;
        this.description = description;
        this.value = value;
    }

    // Property accessors
    public Integer getIdParameter() {
        return this.idParameter;
    }

    public void setIdParameter(Integer idParameter) {
        this.idParameter = idParameter;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public void setParameterKey(String parameterKey) {
        this.parameterKey = parameterKey;
    }

    public String getParameterKey() {
        return this.parameterKey;
    }
}
