/*
 * ReportForm3.java
 *
 * Created on 1 de abril de 2008, 11:43 PM
 */
package sicce.wizard.report.panels;

import java.awt.Component;
import java.awt.Dimension;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import org.netbeans.spi.wizard.WizardController;
import org.netbeans.spi.wizard.WizardPage;
import sicce.api.businesslogic.ClassFactory;
import sicce.api.businesslogic.SicceComboBoxModel;
import sicce.api.info.Field;
import sicce.ui.manager.handlers.FieldHandler;
import sicce.api.businesslogic.FieldsCellRenderer;
import sicce.ui.manager.listeners.JTableButtonMouseListener;
import sicce.api.businesslogic.JTableButtonRenderer;
import sicce.api.businesslogic.ReportFilterTableModel;
import sicce.api.info.interfaces.IFilter;

/**
 *
 * @author  Karu
 */
public class ReportForm4 extends WizardPage {

    private final WizardController controller;
    private final Map wizardData;
    public static final String KEY_SELECTED = "selectedFields";
    public static final String KEY_WHERE = "whereFields";
    private FieldHandler filterField = new FieldHandler();
    SicceComboBoxModel selectedComboBoxModel;
    private ReportFilterTableModel reportTableModel;
    JComboBox operator;
    JButton searchField;
    TableCellRenderer defaultRenderer;
    /** Creates new form ReportDetail */
    public ReportForm4(WizardController controller, Map wizardData) {
        initComponents();
        this.controller = controller;
        this.wizardData = wizardData;
        List filterList = null;
        LoadComboBox();
        reportTableModel = new ReportFilterTableModel(filterList);
        grdSearchFields.setModel(reportTableModel);
        TableColumn operatorColumn = grdSearchFields.getColumnModel().getColumn(1);
        TableColumn searchColumn = grdSearchFields.getColumnModel().getColumn(3);
        operatorColumn.setCellEditor(new DefaultCellEditor(getComboBox()));
        
        defaultRenderer = grdSearchFields.getDefaultRenderer(JButton.class);
        grdSearchFields.setDefaultRenderer(JButton.class,
			       new JTableButtonRenderer(defaultRenderer));
        grdSearchFields.setPreferredScrollableViewportSize(new Dimension(150, 200));
        grdSearchFields.addMouseListener(new JTableButtonMouseListener(grdSearchFields));

    }

    private void LoadComboBox() {
        selectedComboBoxModel = new SicceComboBoxModel(filterField.fillfilterFields());
        cboWhereItems.setModel(selectedComboBoxModel);
        cboWhereItems.setRenderer(new FieldsCellRenderer());
    }

    @Override
    protected String validateContents(Component component, Object event) {

        if (component == null) {
            return "Defina los criterios del reporte...";
        }


        return null;
    }

    public void fillWizardMap() {

        //  wizardData.put(KEY_GROUP, FieldHandler.getListGroupFields());

        if (FieldHandler.getListGroupFields() != null) {
            try {
                controller.setForwardNavigationMode(WizardController.MODE_CAN_FINISH);
                controller.setProblem(null);

            } catch (Exception ex) {
                Logger.getLogger(ReportForm4.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboWhereItems = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdSearchFields = new javax.swing.JTable();

        setName("Form"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.ui.manager.forms.SicceuimanagerApp.class).getContext().getResourceMap(ReportForm4.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboWhereItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboWhereItems.setName("cboWhereItems"); // NOI18N
        cboWhereItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboWhereItemsActionPerformed(evt);
            }
        });
        jPanel1.add(cboWhereItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, -1));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnAdd.setIcon(resourceMap.getIcon("btnAdd.icon")); // NOI18N
        btnAdd.setText(resourceMap.getString("btnAdd.text")); // NOI18N
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        grdSearchFields.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Campo", "Operador", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grdSearchFields.setName("grdSearchFields"); // NOI18N
        jScrollPane1.setViewportView(grdSearchFields);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 340, 150));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 230));
    }// </editor-fold>//GEN-END:initComponents
    private void cboWhereItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboWhereItemsActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_cboWhereItemsActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here: 

        if (cboWhereItems != null) {
            Field fieldSelected = (Field) cboWhereItems.getSelectedItem();            
            IFilter filter = ClassFactory.getFilterInstance();
            filter.setField(fieldSelected);
            reportTableModel.addFilter(filter);
        }
            
}//GEN-LAST:event_btnAddActionPerformed

    private JComboBox getComboBox() {
        if (operator == null) {
            operator = new JComboBox();
            operator.addItem("igual");
            operator.addItem("menor");
            operator.addItem("mayor");
            operator.addItem("diferente");
            operator.addItem("entre");
            operator.addItem("contiene");
        }
        return operator;
    }
    
    private JButton getButtonSearch()
    {
           if (searchField == null)
               searchField.setText("...");
        
           
           return searchField;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox cboWhereItems;
    private javax.swing.JTable grdSearchFields;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
