/*
 * SearchDialog.java
 *
 * Created on February 29, 2008, 12:06 AM
 */
package sicce.ui.manager.controls;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.List;
import javax.swing.ListSelectionModel;
import sicce.api.businesslogic.model.SicceTableModel;
import sicce.api.info.ConstantsProvider.DialogResult;
import sicce.api.util.ComponentUtil;

/**
 *
 * @author  gish@c
 */
public class SearchDialog<T> extends javax.swing.JDialog {

    private SearchPane<T> searchPane;
    private final Dimension PREFERRED_SIZE = new Dimension(500,400);

    /** Creates new form SearchDialog */
    public SearchDialog(java.awt.Frame parent, boolean modal) {
        super(parent, "Búsqueda", modal);
        initComponents();
        this.setSize(PREFERRED_SIZE);
    }

    public SearchDialog(java.awt.Frame parent, boolean modal, SicceTableModel<T> tableModel) {
        this(parent, modal);
        searchPane = new SearchPane<T>(this, tableModel);
        this.getContentPane().add(searchPane, BorderLayout.CENTER);
        ComponentUtil.CenterFormInScreen(this, this.getToolkit());
    }
    
    public SearchDialog(java.awt.Frame parent, boolean modal, SicceTableModel<T> tableModel, int lstModel) {
        this(parent, modal);
        searchPane = new SearchPane<T>(this, tableModel, lstModel);
        this.getContentPane().add(searchPane, BorderLayout.CENTER);
        ComponentUtil.CenterFormInScreen(this, this.getToolkit());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public DialogResult getDialogResult() {
        return searchPane.getDialogResult();
    }

    public T getSearchResult() {
        return searchPane.getSearchResult();
    }
    
    public List<T> getResultList(){
        return searchPane.getResultList();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
