package sicce.api.info;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

import sicce.api.info.auto.AbstractLocation;
import sicce.api.info.interfaces.ILocation;
import sicce.api.info.interfaces.ILocationType;
import sicce.api.info.interfaces.IMeasure;
import sicce.api.info.interfaces.IPowerMeter;
import sicce.api.info.interfaces.IZone;

/**
 * Location generated by MyEclipse Persistence Tools
 */
public class Location extends AbstractLocation implements java.io.Serializable, ILocation {

	// Constructors

	/** default constructor */
	public Location() {
	}

	/** minimal constructor */
	public Location(Integer idLocation, LocationType locationType,
			ILocation location, IPowerMeter powerMeter, String description) {
		super(idLocation, locationType, location, powerMeter, description);
	}

	/** full constructor **/
	public Location(Integer idLocation, LocationType locationType,
			ILocation location, IPowerMeter powerMeter, String description, Set<ILocation> locations, Set<IZone> zones,
			Set<IMeasure> measures) {
		super(idLocation, locationType, location, powerMeter, description,
				locations, zones, measures);
	}

    public Integer getID() {
        return this.idLocation;
    }

}
