package sicce.api.info;

// Generated by MyEclipse Persistence Tools
import sicce.api.info.auto.AbstractUserPowerMeter;

/**
 * Representacion de los usuarios del sistema
 * @author gish@c
 */
public class UserPowerMeter extends AbstractUserPowerMeter implements
        java.io.Serializable {

    // Constructors
    /**
     * Constructor
     */
    public UserPowerMeter() {
    }
}
