package sicce.api.info;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

import sicce.api.info.auto.AbstractZone;
import sicce.api.info.interfaces.ILocation;
import sicce.api.info.interfaces.IOptionSicce;
import sicce.api.info.interfaces.IZone;

/**
 * Zone generated by MyEclipse Persistence Tools
 */
public class Zone extends AbstractZone implements java.io.Serializable, IZone {

	// Constructors

	/** default constructor */
	public Zone() {
	}

	/** minimal constructor */
	public Zone(Integer idZone) {
		super(idZone);
	}

	/** full constructor */
	public Zone(Integer idZone, String code, String description,
			Set<ILocation> locations) {
		super(idZone, code, description, locations);
	}

    public void setID(int id) {
        this.idZone = id;
    }

    public int getID() {
        return this.idZone;
    }


    public Set<ILocation> getLocationsInZone() {
        return this.locations;
    }

    public void setLocationsInZone(Set<ILocation> locationsInZone) {
        this.locations = locationsInZone;
    }

    public Set<IOptionSicce> getLocationsZone() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void addLocations(IOptionSicce locations) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void removeLocations(IOptionSicce locations) {
        throw new UnsupportedOperationException("Not supported yet.");
    }


}
