/*
 * ErrorsPane.java
 *
 * Created on July 20, 2008, 6:44 PM
 */
package sicce.api.processor.viewer.controls;

import java.awt.TrayIcon;
import javax.swing.DefaultListModel;
import sicce.api.processor.Processor;
import sicce.api.processor.viewer.handlers.ExceptionHandler;

/**
 * Panel para mostrar los errores ocurridos durante el monitoreo
 * @author  gish@c
 */
public class ErrorsPane extends DataDisplayer {

    /**
     * Manejador del Tray del sistema
     */
    private TrayIcon trayIcon;
    
    /**
     * Manejador de datos del panel de excepciones
     */
    private ExceptionHandler exceptionHandler;
    /**
     * Modelo de lista para mostrar las excepciones
     */
    private DefaultListModel listModel;

    /**
     * Devuelve el modelo de lista para mostrar las excepciones
     * @return Modelo de lista para mostrar las excepciones
     */
    private DefaultListModel getListModel() {
        if (listModel == null) {
            listModel = new DefaultListModel();
        }
        return listModel;
    }

    /**
     * Constructor
     * @param processor Objeto para procesar las lecturas de los medidores
     */
    public ErrorsPane(Processor processor) {
        initComponents();
        this.processor = processor;
    }

    /**
     * Constructor 
     * @param trayIcon Manejador del Tray del sistema
     * @param processor Objeto para procesar las lecturas de los medidores
     */
    public ErrorsPane(TrayIcon trayIcon, Processor processor) {
        this(processor);
        this.trayIcon = trayIcon;
        this.errorList.setModel(getListModel());
        this.exceptionHandler = new ExceptionHandler(trayIcon, getListModel());
        AttachExceptionHandlerToDataProcessor();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        errorList = new javax.swing.JList();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.api.processor.viewer.SicceapiprocessorviewerApp.class).getContext().getResourceMap(ErrorsPane.class);
        errorList.setFont(resourceMap.getFont("errorList.font")); // NOI18N
        errorList.setForeground(resourceMap.getColor("errorList.foreground")); // NOI18N
        errorList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        errorList.setName("errorList"); // NOI18N
        jScrollPane1.setViewportView(errorList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList errorList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * Agrega el manejador de excepciones como observador de eventos 
     */
    private void AttachExceptionHandlerToDataProcessor() {
        processor.AddObserver(exceptionHandler.getExceptionObserver());
    }
}
