/*
 * ReportForm3.java
 *
 * Created on 1 de abril de 2008, 11:43 PM
 */
package sicce.wizard.report.panels;

import java.awt.Component;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.table.TableColumn;
import javax.swing.text.TableView.TableRow;
import org.netbeans.spi.wizard.WizardController;
import org.netbeans.spi.wizard.WizardPage;
import sicce.api.businesslogic.LocationBizObject;
import sicce.api.businesslogic.LocationTableModel;
import sicce.api.businesslogic.PowerMeterBizObject;
import sicce.api.businesslogic.PowerMeterTableModel;
import sicce.api.businesslogic.SicceComboBoxModel;
import sicce.api.businesslogic.ZoneBizObject;
import sicce.api.businesslogic.ZoneTableModel;
import sicce.api.info.ConstantsProvider.DialogResult;
import sicce.api.info.interfaces.ILocation;
import sicce.api.info.interfaces.IPowerMeter;
import sicce.api.info.interfaces.IZone;
import sicce.ui.manager.controls.JOptionPaneExtended;
import sicce.ui.manager.controls.SearchDialog;
import sicce.api.info.Field;
import sicce.ui.manager.handlers.FieldHandler;
import sicce.api.businesslogic.FieldsCellRenderer;
import sicce.api.businesslogic.FieldsComparator;
import sicce.ui.manager.reports.ReportWizardTableModel;

/**
 *
 * @author  Karu
 */
public class ReportForm4 extends WizardPage {

    private final WizardController controller;
    private final Map wizardData;
    public static final String KEY_SELECTED = "selectedFields";
    public static final String KEY_GROUP = "groupFields";
    ZoneBizObject zoneBizObject;
    LocationBizObject locationBizObject;
    PowerMeterBizObject pmeterBizObject;
    SicceComboBoxModel selectedComboBoxModel;
    ReportWizardTableModel reportTableModel;
    private ILocation plocation;
    private IPowerMeter pmeter;
    private IZone pzone;
    private List selectedField = null;
    private TableRow fieldRow;
    private TableColumn operatorColumn;

    /** Creates new form ReportDetail */
    public ReportForm4(WizardController controller, Map wizardData) {
        initComponents();
        this.controller = controller;
        this.wizardData = wizardData;
        selectedField = (List) wizardData.get(KEY_SELECTED);
        zoneBizObject = new ZoneBizObject();
        locationBizObject = new LocationBizObject();
        pmeterBizObject = new PowerMeterBizObject();
        LoadComboBox();

    }

    private void LoadComboBox() {
        selectedComboBoxModel = new SicceComboBoxModel(selectedField);
        cboWhereItems.setModel(selectedComboBoxModel);
        cboWhereItems.setRenderer(new FieldsCellRenderer());
    }

    @Override
    protected String validateContents(Component component, Object event) {

        if (component == null) {
            return "Defina los criterios del reporte...";
        }


        return null;
    }

    public void fillWizardMap() {

        wizardData.put(KEY_GROUP, FieldHandler.getListGroupFields());

        if (FieldHandler.getListGroupFields() != null) {
            try {
                controller.setForwardNavigationMode(WizardController.MODE_CAN_FINISH);
                controller.setProblem(null);

            } catch (Exception ex) {
                Logger.getLogger(ReportForm4.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboWhereItems = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdSearchFields = new javax.swing.JTable();

        setName("Form"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.ui.manager.forms.SicceuimanagerApp.class).getContext().getResourceMap(ReportForm4.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboWhereItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboWhereItems.setName("cboWhereItems"); // NOI18N
        cboWhereItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboWhereItemsActionPerformed(evt);
            }
        });
        jPanel1.add(cboWhereItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, -1));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnAdd.setIcon(resourceMap.getIcon("btnAdd.icon")); // NOI18N
        btnAdd.setText(resourceMap.getString("btnAdd.text")); // NOI18N
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        grdSearchFields.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Campo", "Operador", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grdSearchFields.setName("grdSearchFields"); // NOI18N
        jScrollPane1.setViewportView(grdSearchFields);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 340, 150));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 230));
    }// </editor-fold>//GEN-END:initComponents
    private void cboWhereItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboWhereItemsActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_cboWhereItemsActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (cboWhereItems != null) {
            
            operatorColumn = grdSearchFields.getColumnModel().getColumn(1);

        JComboBox operator = getComboBox();
        operatorColumn.setCellEditor(new DefaultCellEditor(operator));
        
        
        
        }
            
}//GEN-LAST:event_btnAddActionPerformed

    private JComboBox getComboBox() {
        JComboBox operator = new JComboBox();
        operator.addItem("=");
        operator.addItem("<");
        operator.addItem(">");
        operator.addItem("<>");
        operator.addItem("<>");
        operator.addItem("like");
        return operator;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox cboWhereItems;
    private javax.swing.JTable grdSearchFields;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
