/*
 * ReportDetail.java
 *
 * Created on 31 de marzo de 2008, 10:06 PM
 */

package sicce.wizard.report.panels;

import java.util.Map;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import org.netbeans.spi.wizard.WizardController;
import sicce.ui.manager.forms.*;

/**
 *
 * @author  Karu
 */
public class ReportForm1 extends javax.swing.JPanel {
    
    private final WizardController controller;
    private final Map wizardData;
    public static final String KEY_INFO = "infogeneral";
    public static final String VALUE_NAME = "name";
    public static final String VALUE_DESCRIPTION = "description";
   
    /** Creates new form ReportDetail */
    public ReportForm1 (WizardController controller, Map wizardData) {
         initComponents();
        this.controller = controller;
        this.wizardData = wizardData;
        
        
        controller.setProblem ("No ha ingresado los datos del reporte");
        txtReportName.putClientProperty(KEY_INFO, VALUE_NAME);
        txtDescription.putClientProperty(KEY_INFO, VALUE_DESCRIPTION);
                
                
          
                
                
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtReportName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), null));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtReportName.setName("txtReportName"); // NOI18N
        txtReportName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtReportName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 250, 20));

        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setName("txtDescription"); // NOI18N
        txtDescription.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDescriptionPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 250, -1));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.ui.manager.forms.SicceuimanagerApp.class).getContext().getResourceMap(ReportForm1.class);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void txtReportNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportNameActionPerformed
        JTextField field = (JTextField) evt.getSource();
        wizardData.put (KEY_INFO, field.getClientProperty(KEY_INFO));
        controller.setProblem(null);
}//GEN-LAST:event_txtReportNameActionPerformed

    private void txtDescriptionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDescriptionPropertyChange
        // TODO add your handling code here:
        JTextArea field = (JTextArea) evt.getSource();
        wizardData.put (KEY_INFO, field.getClientProperty(KEY_INFO));
        controller.setProblem(null);
        if (field!= null) {
            controller.setForwardNavigationMode(controller.MODE_CAN_CONTINUE);
        }      
    }//GEN-LAST:event_txtDescriptionPropertyChange
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtReportName;
    // End of variables declaration//GEN-END:variables
    
}
