/*
 * ReportForm3.java
 *
 * Created on 1 de abril de 2008, 11:43 PM
 */
package sicce.wizard.report.panels;

import java.awt.Component;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.netbeans.spi.wizard.WizardController;
import org.netbeans.spi.wizard.WizardPage;
import sicce.api.businesslogic.LocationBizObject;
import sicce.api.businesslogic.LocationTableModel;
import sicce.api.businesslogic.PowerMeterBizObject;
import sicce.api.businesslogic.PowerMeterTableModel;
import sicce.api.businesslogic.ZoneBizObject;
import sicce.api.businesslogic.ZoneTableModel;
import sicce.api.info.ConstantsProvider.DialogResult;
import sicce.api.info.interfaces.ILocation;
import sicce.api.info.interfaces.IPowerMeter;
import sicce.api.info.interfaces.IZone;
import sicce.ui.manager.controls.JOptionPaneExtended;
import sicce.ui.manager.controls.SearchDialog;
import sicce.ui.manager.reports.Field;
import sicce.ui.manager.reports.FieldHandler;
import sicce.ui.manager.reports.FieldsCellRenderer;
import sicce.ui.manager.reports.FieldsComparator;

/**
 *
 * @author  Karu
 */
public class ReportForm3 extends WizardPage {

    private final WizardController controller;
    private final Map wizardData;
    public static final String KEY_SELECTED = "selectedFields";
    public static final String KEY_GROUP = "groupFields";
    ZoneBizObject zoneBizObject;
    LocationBizObject locationBizObject;
    PowerMeterBizObject pmeterBizObject;
    private ILocation plocation;
    private IPowerMeter pmeter;
    private IZone pzone;
    private List selectedField = null;
  
    /** Creates new form ReportDetail */
    public ReportForm3(WizardController controller, Map wizardData) {
        initComponents();
        this.controller = controller;
        this.wizardData = wizardData;     
        selectedField = (List) wizardData.get(KEY_SELECTED);
        fillSelectedFields(); 
        zoneBizObject = new ZoneBizObject();
        locationBizObject = new LocationBizObject();
        pmeterBizObject = new PowerMeterBizObject();
      
       
    }

    public void fillSelectedFields() {
      
      lstSelectedFields.setCellRenderer(new FieldsCellRenderer());
      lstSelectedFields.setListData(selectedField.toArray());
    }

   
    
    public void updateLists(){
      lstGroupFields.setCellRenderer(new FieldsCellRenderer());
      lstSelectedFields.setListData(FieldHandler.getSelectedFields().toArray());
      lstGroupFields.setListData(FieldHandler.getListGroupFields().toArray());
    
    }

      @Override
    protected String validateContents(Component component, Object event) {

        if (component == null) {
            return "Defina los criterios del reporte...";
        }

      
        return null;
    }

     public void fillWizardMap(){
        
        wizardData.put (KEY_GROUP, FieldHandler.getListGroupFields());  
      
        if (FieldHandler.getListGroupFields()!= null) {
            try {          
                controller.setForwardNavigationMode(WizardController.MODE_CAN_FINISH);
                controller.setProblem(null);
                
            } catch (Exception ex) {
                Logger.getLogger(ReportForm3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }      
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGroupFields = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSelectedFields = new javax.swing.JList();
        btnUp = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAddField = new javax.swing.JButton();
        btnRemoveField = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtZone = new javax.swing.JTextField();
        btnSearchZone = new javax.swing.JButton();
        btnClearZone = new javax.swing.JButton();
        txtLocation = new javax.swing.JTextField();
        btnSearchLocation = new javax.swing.JButton();
        btnClearLocation = new javax.swing.JButton();
        txtPowerMeter = new javax.swing.JTextField();
        btnSearchPowerMeter = new javax.swing.JButton();
        btnClearPowerMeter = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sicce.ui.manager.forms.SicceuimanagerApp.class).getContext().getResourceMap(ReportForm3.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), null)); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstGroupFields.setName("lstGroupFields"); // NOI18N
        lstGroupFields.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGroupFieldsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstGroupFields);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 140, 170));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        lstSelectedFields.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lstSelectedFields.setName("lstSelectedFields"); // NOI18N
        jScrollPane2.setViewportView(lstSelectedFields);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 170));

        btnUp.setIcon(resourceMap.getIcon("btnUp.icon")); // NOI18N
        btnUp.setName("btnUp"); // NOI18N
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 30, 30));

        btnDown.setIcon(resourceMap.getIcon("btnDown.icon")); // NOI18N
        btnDown.setName("btnDown"); // NOI18N
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });
        jPanel1.add(btnDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 30, 30));

        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 110, -1));

        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        btnAddField.setIcon(resourceMap.getIcon("btnAddField.icon")); // NOI18N
        btnAddField.setName("btnAddField"); // NOI18N
        btnAddField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFieldActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 40, 30));

        btnRemoveField.setIcon(resourceMap.getIcon("btnRemoveField.icon")); // NOI18N
        btnRemoveField.setName("btnRemoveField"); // NOI18N
        btnRemoveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFieldActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoveField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 40, 30));

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 110, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 400, 220));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel2.border.titleColor"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtZone.setText(resourceMap.getString("txtZone.text")); // NOI18N
        txtZone.setName("txtZone"); // NOI18N
        txtZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZoneActionPerformed(evt);
            }
        });
        jPanel2.add(txtZone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 240, -1));

        btnSearchZone.setIcon(resourceMap.getIcon("btnSearchZone.icon")); // NOI18N
        btnSearchZone.setAlignmentX(0.5F);
        btnSearchZone.setAlignmentY(1.5F);
        btnSearchZone.setName("btnSearchZone"); // NOI18N
        btnSearchZone.setPreferredSize(new java.awt.Dimension(50, 21));
        btnSearchZone.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSearchZone.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearchZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchZoneActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearchZone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 30, -1));

        btnClearZone.setIcon(resourceMap.getIcon("btnClearZone.icon")); // NOI18N
        btnClearZone.setName("btnClearZone"); // NOI18N
        btnClearZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearZoneActionPerformed(evt);
            }
        });
        jPanel2.add(btnClearZone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 30, -1));

        txtLocation.setText(resourceMap.getString("txtLocation.text")); // NOI18N
        txtLocation.setName("txtLocation"); // NOI18N
        jPanel2.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, 240, -1));

        btnSearchLocation.setIcon(resourceMap.getIcon("btnSearchLocation.icon")); // NOI18N
        btnSearchLocation.setAlignmentX(0.5F);
        btnSearchLocation.setAlignmentY(1.5F);
        btnSearchLocation.setName("btnSearchLocation"); // NOI18N
        btnSearchLocation.setPreferredSize(new java.awt.Dimension(50, 21));
        btnSearchLocation.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSearchLocation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearchLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLocationActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearchLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 45, 30, -1));

        btnClearLocation.setIcon(resourceMap.getIcon("btnClearLocation.icon")); // NOI18N
        btnClearLocation.setName("btnClearLocation"); // NOI18N
        btnClearLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLocationActionPerformed(evt);
            }
        });
        jPanel2.add(btnClearLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 45, 30, -1));

        txtPowerMeter.setText(resourceMap.getString("txtPowerMeter.text")); // NOI18N
        txtPowerMeter.setName("txtPowerMeter"); // NOI18N
        jPanel2.add(txtPowerMeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 240, -1));

        btnSearchPowerMeter.setIcon(resourceMap.getIcon("btnSearchPowerMeter.icon")); // NOI18N
        btnSearchPowerMeter.setAlignmentX(0.5F);
        btnSearchPowerMeter.setAlignmentY(1.5F);
        btnSearchPowerMeter.setName("btnSearchPowerMeter"); // NOI18N
        btnSearchPowerMeter.setPreferredSize(new java.awt.Dimension(50, 21));
        btnSearchPowerMeter.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSearchPowerMeter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearchPowerMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPowerMeterActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearchPowerMeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 30, -1));

        btnClearPowerMeter.setIcon(resourceMap.getIcon("btnClearPowerMeter.icon")); // NOI18N
        btnClearPowerMeter.setName("btnClearPowerMeter"); // NOI18N
        btnClearPowerMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPowerMeterActionPerformed(evt);
            }
        });
        jPanel2.add(btnClearPowerMeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 30, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFieldActionPerformed
        // TODO add your handling code here:
        Object[] field = this.lstSelectedFields.getSelectedValues();
        Field tmp = null;
       
        for (int i = 0; i < field.length; i++) {
            tmp = (Field) field[i];
            if (FieldHandler.CompareList(tmp , FieldHandler.getListGroupFields())){
                JOptionPaneExtended.showMessageDialog(this, "El campo " + tmp.getTitle() + " ya ha sido agregado.");
                return;
            } else {
                FieldHandler.addGroupField(tmp);
            }
        }
        updateLists();
      //  fillWizardMap(evt);
        
}//GEN-LAST:event_btnAddFieldActionPerformed

    private void btnRemoveFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFieldActionPerformed
        // TODO add your handling code here:
        Object[] field = this.lstGroupFields.getSelectedValues();
        Field tmp = null;

        for (int i = 0; i < field.length; i++) {
            tmp = (Field) field[i];
         FieldHandler.removeGroupField(tmp);
        }
        updateLists();
      //  fillWizardMap(evt);
        
    }//GEN-LAST:event_btnRemoveFieldActionPerformed

    private void lstGroupFieldsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGroupFieldsValueChanged
        // TODO add your handling code here:
        fillWizardMap();
    }//GEN-LAST:event_lstGroupFieldsValueChanged

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
         if(lstGroupFields.getSelectedValue()==null){
            JOptionPaneExtended.showMessageDialog(this, "Debe seleccionar un valor de la lista");
            return;
        }
         
       int index = lstGroupFields.getSelectedIndex();
        
        if (index > 0)
        {
            Field previous = (Field) lstGroupFields.getModel().getElementAt(index - 1 );
            Field selected = (Field) lstGroupFields.getModel().getElementAt(index);
            previous.setOrder(previous.getOrder() + 1);
            selected.setOrder(selected.getOrder() - 1);
            Collections.sort(FieldHandler.getListGroupFields(), new FieldsComparator());
            updateLists();
            lstGroupFields.setSelectedIndex(index - 1);
        }
  
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        // TODO add your handling code here:
        if(lstGroupFields.getSelectedValue()==null){
            JOptionPaneExtended.showMessageDialog(this, "Debe seleccionar un valor de la lista");
            return;
        }
         
       int index = lstGroupFields.getSelectedIndex();
        
        if (index < lstGroupFields.getModel().getSize() - 1 )
        {
            Field selected = (Field) lstGroupFields.getModel().getElementAt(index);
            Field next = (Field) lstGroupFields.getModel().getElementAt(index + 1 );
            selected.setOrder(selected.getOrder() + 1);
            next.setOrder(next.getOrder() - 1);
            
            Collections.sort(FieldHandler.getListGroupFields(), new FieldsComparator());
            updateLists();
            lstGroupFields.setSelectedIndex(index + 1);
        }
       
       
    }//GEN-LAST:event_btnDownActionPerformed

    private void txtZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZoneActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtZoneActionPerformed

    private void btnSearchZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchZoneActionPerformed
        SearchDialog<IZone> searchZoneDialog = new SearchDialog<IZone>(new JFrame(), true, new ZoneTableModel(zoneBizObject.GetAllZones()));
        searchZoneDialog.setVisible(true);
        DialogResult result = searchZoneDialog.getDialogResult();
        if (result == DialogResult.Ok) {
            pzone = searchZoneDialog.getSearchResult();
            if (pzone != null) {
                txtZone.setText(pzone.getDescription());
            }
        }
}//GEN-LAST:event_btnSearchZoneActionPerformed

    private void btnClearZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearZoneActionPerformed
        pzone = null;
        txtZone.setText("");
}//GEN-LAST:event_btnClearZoneActionPerformed

    private void btnSearchLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLocationActionPerformed
        SearchDialog<ILocation> searchLocationDialog = new SearchDialog<ILocation>(new JFrame(), true, new LocationTableModel(locationBizObject.GetAllLocations()));
        searchLocationDialog.setVisible(true);
        DialogResult result = searchLocationDialog.getDialogResult();
        if (result == DialogResult.Ok) {
            plocation = searchLocationDialog.getSearchResult();
            if (plocation != null) {
                txtLocation.setText(plocation.getDescription());
            }
        }
        
}//GEN-LAST:event_btnSearchLocationActionPerformed

    private void btnClearLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLocationActionPerformed
       plocation = null;
       txtLocation.setText("");
}//GEN-LAST:event_btnClearLocationActionPerformed

    private void btnSearchPowerMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPowerMeterActionPerformed
        SearchDialog<IPowerMeter> searchPowerMeterDialog = new SearchDialog<IPowerMeter>(new JFrame(), true, new PowerMeterTableModel(pmeterBizObject.GetAllPowerMeter()));
        searchPowerMeterDialog.setVisible(true);
        DialogResult result = searchPowerMeterDialog.getDialogResult();
        if (result == DialogResult.Ok) {
           pmeter = searchPowerMeterDialog.getSearchResult();
            if (pmeter != null) {
                txtPowerMeter.setText(pmeter.getDescription());
            }
        }      
        
}//GEN-LAST:event_btnSearchPowerMeterActionPerformed

    private void btnClearPowerMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPowerMeterActionPerformed
        pmeter =null;
        txtPowerMeter.setText("");
}//GEN-LAST:event_btnClearPowerMeterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddField;
    private javax.swing.JButton btnClearLocation;
    private javax.swing.JButton btnClearPowerMeter;
    private javax.swing.JButton btnClearZone;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnRemoveField;
    private javax.swing.JButton btnSearchLocation;
    private javax.swing.JButton btnSearchPowerMeter;
    private javax.swing.JButton btnSearchZone;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstGroupFields;
    private javax.swing.JList lstSelectedFields;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtPowerMeter;
    private javax.swing.JTextField txtZone;
    // End of variables declaration//GEN-END:variables
}
