package sicce.api.info.auto;

import java.util.HashSet;
import java.util.Set;
import sicce.api.info.interfaces.IOptionSicce;
import sicce.api.info.interfaces.IUserSicce;

/**
 * AbstractRole generated by MyEclipse Persistence Tools
 */

public abstract class AbstractRole implements java.io.Serializable {

	// Fields

	protected Integer idRole;
	protected String description;	
	protected Set<IUserSicce> usersInRole = new HashSet<IUserSicce>(0);
	protected Set<IOptionSicce> permissions = new HashSet<IOptionSicce>(0);

	// Constructors

	/** default constructor */
	public AbstractRole() {
	}

	/** minimal constructor */
	public AbstractRole(Integer idRole) {
		this.idRole = idRole;
	}

	/** full constructor */
	public AbstractRole(Integer idRole, String description,
			Set<IUserSicce> usersInRole, Set<IOptionSicce> permissions) {
		this.idRole = idRole;
		this.description = description;
		this.usersInRole = usersInRole;
		this.permissions = permissions;
	}

	// Property accessors

	public Integer getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Integer idRole) {
		this.idRole = idRole;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<IUserSicce> getUsersInRole() {
		return this.usersInRole;
	}

	public void setUsersInRole(Set<IUserSicce> usersInRole) {
		this.usersInRole = usersInRole;
	}

        public Set<IOptionSicce> getPermissions() {
		return this.permissions;
	}
        
	public void setPermissions(Set<IOptionSicce> permissions) {
		this.permissions = permissions;
	}

}