package sicce.api.info.auto;

import java.net.Socket;
import java.util.HashSet;
import java.util.Set;

import sicce.api.info.interfaces.IAlarm;
import sicce.api.info.interfaces.ILocation;
import sicce.api.info.interfaces.IMeasure;
import sicce.api.info.interfaces.IPowerMeter;

/**
 * AbstractPowerMeter generated by MyEclipse Persistence Tools
 */
public abstract class AbstractPowerMeter implements java.io.Serializable, IPowerMeter {

    // Fields
    protected Integer idPowerMeter;
    protected String description;
    protected String ipAddress;
    protected Byte logStatus;
    protected String serial;
    protected String deviceID;
    protected Byte status2;
    protected Set<IMeasure> measures = new HashSet<IMeasure>(0);
    protected Set<ILocation> locations = new HashSet<ILocation>(0);
    protected Set<IAlarm> alarms = new HashSet<IAlarm>(0);
    protected Socket socket;
    

    // Constructors
    /** default constructor */
    public AbstractPowerMeter() {
    }

    /** minimal constructor */
    public AbstractPowerMeter(Integer idPowerMeter) {
        this.idPowerMeter = idPowerMeter;
    }

    // full constructor 
    public AbstractPowerMeter(Integer idPowerMeter, String description,
            String ipAddress, Byte logStatus, String serial, Byte status2,
            Set<IMeasure> measures, Set<ILocation> locations) {
        this.idPowerMeter = idPowerMeter;
        this.description = description;
        this.ipAddress = ipAddress;
        this.logStatus = logStatus;
        this.serial = serial;
        this.status2 = status2;
        this.measures = measures;
        this.locations = locations;
    }

    // Property accessors
    public Integer getIdPowerMeter() {
        return this.idPowerMeter;
    }

    public void setIdPowerMeter(Integer idPowerMeter) {
        this.idPowerMeter = idPowerMeter;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public Byte getLogStatus() {
        return this.logStatus;
    }

    public void setLogStatus(Byte logStatus) {
        this.logStatus = logStatus;
    }

    public String getSerial() {
        return this.serial;
    }

    public void setSerial(String serial) {
        this.serial = serial;
    }

    public Byte getStatus2() {
        return this.status2;
    }

    public void setStatus2(Byte status2) {
        this.status2 = status2;
    }

    public Set<IMeasure> getMeasures() {
        return this.measures;
    }

    public void setMeasures(Set<IMeasure> measures) {
        this.measures = measures;
    }

    public Set<ILocation> getLocations() {
        return this.locations;
    }

    public void setLocations(Set<ILocation> locations) {
        this.locations = locations;
    }
    
    public Set<IAlarm> getAlarms() {
        return alarms;
    }

    public void setAlarms(Set<IAlarm> alarms) {
        this.alarms = alarms;
    }
    
    public void setDeviceID(String deviceID){
        this.deviceID = deviceID;
    }
    
    public String getDeviceID(){
        return this.deviceID;
    }
    
    public Socket getSocket() {
        return this.socket;
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
    }
            
}
