package sicce.api.info.auto;

import java.util.HashSet;
import java.util.Set;

import sicce.api.info.interfaces.ILocation;

/**
 * AbstractZone generated by MyEclipse Persistence Tools
 */

public abstract class AbstractZone implements java.io.Serializable {

	// Fields

	protected Integer idZone;
	protected String code;
	protected String description;
	protected Set<ILocation> locations = new HashSet<ILocation>(0);

	// Constructors

	/** default constructor */
	public AbstractZone() {
	}

	/** minimal constructor */
	public AbstractZone(Integer idZone) {
		this.idZone = idZone;
	}

	/** full constructor */
	public AbstractZone(Integer idZone, String code, String description,
			Set<ILocation> locations) {
		this.idZone = idZone;
		this.code = code;
		this.description = description;
		this.locations = locations;
	}

	// Property accessors

	public Integer getIdZone() {
		return this.idZone;
	}

	public void setIdZone(Integer idZone) {
		this.idZone = idZone;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ILocation> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<ILocation> locations) {
		this.locations = locations;
	}

}